server:
  port: 7200

spring:
  application:
    name: ribbon-eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: ribbon-eureka-hostname
    #访问路径可以显示IP地址
    prefer-ip-address: true
