server:
  port: 8110
spring:
  application:
    name: eureka-server-hystrix
eureka:
  client:
    #false 表示不向注册中心注册自己 ，默认true，
    fetch-registry: false
    # 默认true,false表示自己端就是注册中心，职责是维护服务实例，不需要检索服务
    register-with-eureka: false
  instance:
    instance-id: hystrix8110
    #访问路径可以显示IP地址
    prefer-ip-address: true
