server:
  port: 7600

spring:
  application:
    name: ribbon-eureka-consumer
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7200/eureka/
  instance:
    instance-id: consumer7600
    #访问路径显示IP地址
    prefer-ip-address: true

ribbon-eureka-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡规则全类名
