server:
  port: 7400

spring:
  application:
    name: ribbon-eureka-provider
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7200/eureka/
  instance:
    instance-id: provider7400
    #访问路径显示IP地址
    prefer-ip-address: true

