server:
  port: 8001
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://replica2:8004/eureka/
  instance:
    hostname: eureka-replica1
    #访问路径可以显示IP地址
    prefer-ip-address: true
#  server:
#    enable-self-preservation: false

#eureka:
#  client:
#    #false 表示不向注册中心注册自己 ，默认true，
#    register-with-eureka: false
#    # 默认true,false表示自己端就是注册中心，职责是维护服务实例，不需要检索服务
#    fetch-registry: false

